syntax on
set showmode                  
set nowrap                    
set tabstop=4                  
set softtabstop=4                             
set shiftwidth=4               
set shiftround                  
set backspace=indent,eol,start  
set autoindent                
set copyindent                 
set number                     
set ignorecase                
set smartcase                   
set smarttab  
set visualbell                  
set noerrorbells                
set mouse=a
set showcmd
set clipboard=unnamed
